Homework 2 (p8105)
================
Sanyu Takirambudde (stt2133)
2026-10-07

# Problem 1

``` r
subway_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", 
           na = c("", "NA", ".")) |>
  janitor::clean_names() |>
  select(line, station_name, station_latitude, station_longitude, route1, 
         route2, route3, route4, route5, route6, route7, route8, route9,
         route10, route11, entry, vending, entrance_type, ada) |>
  mutate(entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The NYC subway dataset contains 19 variables: line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entry,
vending, entrance_type, ada. All variable name (the column names in the
dataframe) were converted to lower snake case, and only the variables
listed above were retained. The entry variable was originally imported
as a character variable (YES vs. NO) and was subsequently converted to a
logical variable (TRUE vs. FALSE). The dimensions of the resulting
dataset was 1868 rows x 19 columns. At this point, the dataset is not
tidy. Route information is spread across 11 columns (route1 through
route11), so the route number is stored in the column names instead of
in its own variable, and most of those cells are empty.

``` r
distinct_stations = subway_df |> 
                      distinct(station_name, line)

ada_stations = subway_df |>
                filter(ada == TRUE) |>
                distinct(station_name, line)

no_vending = subway_df |> 
              filter(vending == "NO") |>
              pull(entry)
```

There are 465 distinct stations in the subway dataset. 84 stations are
ADA compliant. The proportion of station entrances and exits without
vending that allow entrance is 0.38.

``` r
subway_tidy = subway_df |> 
                mutate(
                  route8  = as.character(route8), 
                  route9  = as.character(route9), 
                  route10 = as.character(route10), 
                  route11 = as.character(route11) 
                ) |>
                pivot_longer(
                  route1:route11,
                  names_to = "route_number",
                  values_to = "route_name")

a_stations = subway_tidy |>
                filter(route_name == "A") |> 
                distinct(station_name, line)

ada_a_stations = subway_tidy |>
                   filter(route_name == "A" & ada == TRUE) |> 
                   distinct(station_name, line)
```

60 distinct stations serve the A train. Of the stations, 17 are ADA
compliant.

# Problem 2

### Read and clean the Mr. Trash Wheel sheet

``` r
mtw_df = 
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
             sheet = 1,
             range = "A2:N742") |>
  janitor::clean_names() |>
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls))
```

``` r
ptw_df = 
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
             sheet = 2,
             range = "A2:M139") |>
  janitor::clean_names()
```

``` r
gwy_df = 
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
             sheet = 4,
             range = "A2:L394") |>
  janitor::clean_names()
```

``` r
mtw_df = mtw_df |> 
          mutate(
            trash_wheel = "mr",
            year = as.numeric(year))
          
ptw_df = ptw_df |> 
          mutate(
            trash_wheel = "professor",
            plastic_bottles = as.numeric(plastic_bottles))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.numeric(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwy_df = gwy_df |> mutate(trash_wheel = "gwynda")

trash_wheel_df = bind_rows(mtw_df, ptw_df, gwy_df) 
```

There are 1269 observation in the resulting dataset. Key variables
include the name of the corresponding Trash Wheel, the date of data
collection, physical measurements (such as weight and volume) and
quantities of seven different item types collected (e.g., plastic
bottles, cigarette butts, sports balls, wrappers). For available data,
Professor Trash Wheel collected a total of 294.96 tons of trash. In June
of 2022, Gwynnda collected a total of 18120 cigarette butts.

# Problem 3

## Import, Clean, and Tidy Baseline Demographics Dataset

``` r
baseline_raw_df = 
  read_csv("data/MCI_baseline.csv",
           skip = 1,
           na = ".") |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(sex, 
                      1 ~ "male", 
                      0 ~ "female"),
    apoe4 = case_match(apoe4, 
                      1 ~ "carrier", 
                      0 ~ "non-carrier"))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df = baseline_raw_df |>
  filter(age_at_onset > current_age | is.na(age_at_onset))
```

The MCI_baseline.csv dataset was first imported as baseline_raw_df,
including all participants before inclusion criteria was assessed. The
first row was skipped because it contained variable descriptions and
coding schemes for each corresponding column. Any value in the dataset
that consisted solely of a single period (“.”), was interpreted as a
missing value during the import. Thereafter, column names were converted
to lower snake case. The values of the two binary variables (sex, apoe4
were converted from numeric 1 vs. 0 codes to descriptive character
strings (male/female and carrier/non-carrier). In order to apply
inclusion criteria, baseline_df was created to remove any participants
who did not meet the stated inclusion criteria. This was accomplished by
dropping all rows of observations in which that participants current_age
was greater than their age_at_onset, indicating that the participant had
already developed MCI at baseline. In total, 483 participants were
recruited. After excluding 4 participants who did not meet the inclusion
criteria, 479 participants remained. Of of these, 93 went on to develop
MCI. The average age at baseline was 65 years. 30% of the women in the
study were APOE4 carriers.

``` r
amyloid_df = 
  read_csv("data/mci_amyloid.csv",
           skip = 1,
           na = c("NA", "Na")) |>
  janitor::clean_names() |>
  rename(time_0 = baseline) |>
  pivot_longer(
    time_0:time_8,
    names_to = "time",
    names_prefix = "time_",
    values_to = "amyloid_ratio")
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The mci_amyloid.csv dataset was imported as amyloid_df. The first row
was again skipped as it contained a variable description. Any value in
the dataset that consisted solely of “NA” or “Na” was interpreted as a
missing value during the import. Thereafter, column names were converted
to lower snake case. The name of the baseline column was renamed time_0
to match with the names of the other amyloid ratio columns. The
resulting dataset has 2435 observations in the resulting dataset. There
are 3 variables: study_id, time, amyloid_ratio.

``` r
amyloid_df =
  rename(amyloid_df,
         id = study_id)

mci_df = inner_join(
          baseline_df, amyloid_df, by = "id") 
```

There were 8 participants that were only in the baseline dataset and 16
participants that were only in amyloid dataset.

After combining the demographic and biomarker datasets to retain only
participants who appear in both, the resulting mci_df consisted of 2355
observations of 471 participants and 8 different variables including all
unique variables from the amyloid_df and mci_baseline_df datasets,
namely: id, current_age, sex, education, apoe4, age_at_onset, time,
amyloid_ratio.

``` r
write_csv(mci_df, "data/mci.csv")
```
